-- Fix compras table columns
ALTER TABLE compras ADD COLUMN IF NOT EXISTS compra_id TEXT DEFAULT '';
ALTER TABLE compras ADD COLUMN IF NOT EXISTS ingrediente_id TEXT DEFAULT '';
ALTER TABLE compras ADD COLUMN IF NOT EXISTS ingrediente TEXT DEFAULT '';
ALTER TABLE compras ADD COLUMN IF NOT EXISTS proveedor TEXT DEFAULT '';
ALTER TABLE compras ADD COLUMN IF NOT EXISTS cantidad NUMERIC DEFAULT 0;
ALTER TABLE compras ADD COLUMN IF NOT EXISTS unidad TEXT DEFAULT '';
ALTER TABLE compras ADD COLUMN IF NOT EXISTS costo_unitario NUMERIC DEFAULT 0;
ALTER TABLE compras ADD COLUMN IF NOT EXISTS costo_total NUMERIC DEFAULT 0;
ALTER TABLE compras ADD COLUMN IF NOT EXISTS notas TEXT DEFAULT '';
ALTER TABLE compras ADD COLUMN IF NOT EXISTS fecha DATE DEFAULT CURRENT_DATE;
